name: Update Mikrotik CNIP

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (Strong Pull)
        # 使用 actions/checkout@v4 来拉取代码
        uses: actions/checkout@v4
        with:
          # 确保拉取所有历史记录
          fetch-depth: 0
          # 强制拉取子模块和所有内容，解决找不到 scripts/ 的问题
          submodules: true 
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate Mikrotik CNIP list
        run: |
          # 再次检查 scripts 目录内容，用于最终确认
          echo "Listing scripts/ directory content:"
          ls -l scripts/
          
          # 运行脚本
          python3 scripts/generate_mikrotik_cnip.py

      - name: Commit and push changes (Git CLI)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 确保 output/ 目录被追踪
          git add output/
          
          # 尝试提交
          git commit -m "Auto update Mikrotik CNIP list" || echo "No changes to commit"
          
          # 推送更改
          git push
