- name: Commit and push changes (via Git CLI)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 复制生成的 output 文件到仓库根目录进行提交
          # 假设 output 目录是在工作目录的根部生成的
          cp -r output .
          
          # 暂存所有更改
          git add output/
          
          # 尝试提交，如果文件没有变化，则会打印 "No changes to commit"
          git commit -m "Auto update Mikrotik CNIP list" || echo "No changes to commit"
          
          # 推送更改
          git push
